# Generated by Django 5.0.1 on 2024-01-14 07:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTrip",
            fields=[
                (
                    "trip_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "user_id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("vessel", models.CharField(max_length=255)),
                ("date", models.DateField()),
                (
                    "departure", 
                    models.IntegerField(choices=[
                        (1, 'IRO'),
                        (2, 'CVC'),
                        (3, 'SNL'),
                        (4, 'KGN'),
                        (5, 'CARP'),
                        (6, 'GAN'),
                        (7, 'MOR'),
                        (8, 'PRS'),
                        (9, 'PRSA'),
                        (10, 'WSH'),
                        (11, 'Other')
                    ])
                ),
                ("destination", 
                    models.IntegerField(choices=[
                        (1, 'IRO'),
                        (2, 'CVC'),
                        (3, 'SNL'),
                        (4, 'KGN'),
                        (5, 'CARP'),
                        (6, 'GAN'),
                        (7, 'MOR'),
                        (8, 'PRS'),
                        (9, 'PRSA'),
                        (10, 'WSH'),
                        (11, 'Other')
                    ])
                ),
                (
                    "trip_type",
                    models.IntegerField(choices=[(1, "Full"), (2, "Partial"), (3, "Cancel")], default=1),
                ),
                ("double", models.BooleanField()),
                ("notes", models.CharField(max_length=255)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "usertrip",
                "verbose_name_plural": "usertrips",
                "abstract": False,
            },
        ),
    ]
