name: Code Formatting Check

on:
  pull_request:
    branches:
      - main

jobs:
  format-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      working-directory: pilot-website/
      run: npm install

    - name: Check Code Formatting
      working-directory: pilot-website/
      run: npm run format-check
