name: Upload Website

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Install dependencies
        run: npm install
        working-directory: frontend/pilot-website/

      - name: Build app
        run: npm run build
        working-directory: frontend/pilot-website/

      - name: Upload to S3
        uses: jyronbones/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          SOURCE_DIR: frontend/pilot-website/build/
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
