name: Zappa Update Dev

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-zappa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install zappa
          pip install -r requirements.txt
        working-directory: ./backend

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_ZAPPA }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_ZAPPA }}
          aws-region: ${{ secrets.AWS_REGION}}

      - name: Update Zappa deployment
        run: |
          zappa update dev --aws-access-key-id ${{ secrets.AWS_ACCESS_KEY_ID_ZAPPA }} --aws-secret-access-key ${{ secrets.AWS_SECRET_ACCESS_KEY_ZAPPA }}
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION_ZAPPA }}
          AWS_REGION: ${{ secrets.AWS_REGION_ZAPPA }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID_ZAPPA }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY_ZAPPA }}
        working-directory: ./backend
