name: Zappa Update Dev

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  update-zappa:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.11"

      - name: Install dependencies and update Zappa deployment
        run: |
          python -m pip install --upgrade pip
          pip install virtualenv
          python -m venv venv
          source venv/bin/activate
          pip install zappa
          pip install -r requirements.txt
          export AWS_DEFAULT_REGION=us-east-1
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID_ZAPPA }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY_ZAPPA }}
          zappa update dev
        working-directory: ./backend
