name: Zappa Update Dev

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy-django-serverless:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Setting up AWS Credentials
        run: |
          pip install awscli
          aws configure set region us-east-1
          aws configure set output json
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID_ZAPPA }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY_ZAPPA }}

      - name: Create virtual env with Python3.11
        run: |
          pip install virtualenv
          python3.11 -m virtualenv env
        working-directory: ./backend

      - name: Install Requirements
        run: |
          . env/bin/activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # The path is relative to the working-directory
          deactivate
        working-directory: ./backend

      - name: Install Zappa
        run: |
          . env/bin/activate
          pip install zappa
          deactivate
        working-directory: ./backend

      - name: Update Django application using zappa
        run: |
          . env/bin/activate
          zappa update dev
          deactivate
        working-directory: ./backend
